### ISSUE TITLE
anybaseocr-deskew wrong coordinates

### ISSUE THREAD

**Issue by EEngl52** [mjenckel/ocrd_anybaseocr#51] opened 2020-03-04 09:57 UTC
when deskewing with ocrd-anybaseocr-deskew the coordinates from the Alternative Image produced in this process seem to be used for all further steps. In the end, the coordinates of all regions, lines, words etc. are wrong, even though the text is fully detected.
[kit3.zip](https://github.com/OCR-D/ocrd_anybaseocr/files/4286610/kit3.zip)

**Comment by bertsky** [comment] 2020-04-06 10:29
duplicate of #47

**Closed as completed** 2020-06-08 10:06 UTC
Labels: duplicate
